# This container is used to run e2e tests against the built API container
FROM node:22

COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json

WORKDIR /app

RUN npm ci

COPY . .

CMD /bin/bash -c "npm run setup && npm run test:integration"
