on:
  push:
    branches:
      - master
  workflow_dispatch:

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: googleapis/release-please-action@v5
        id: release
        with:
          release-type: node
          token: ${{ secrets.GHA_NODEJS_TOKEN }}
      # The logic below handles the npm publication:
      - uses: actions/checkout@v6
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"
          package-manager-cache: false
        if: ${{ steps.release.outputs.release_created }}
      - run: npm ci
        if: ${{ steps.release.outputs.release_created }}
      - run: npm publish --access public
        if: ${{ steps.release.outputs.release_created }}
